export default {
    GET_EXAMS: "GET_EXAMS",
    ADD_EXAM: "ADD_EXAM",
    UPDATE_EXAM: "UPDATE_EXAM",
    GET_EXAMS_BY_USER: "GET_EXAMS_BY_USER",
    ENROLL_USER_EXAM: "ENROLL_USER_EXAM",
    DELETE_USER_EXAM: "DELETE_USER_EXAM",
    GET_USEREXAM_BY_ID:"GET_USEREXAM_BY_ID"
};
