export default {
    GET_EXAMS: "GET_EXAMS",
    ADD_EXAM: "ADD_EXAM",
    UPDATE_EXAM: "UPDATE_EXAM",
    GET_EXAMS_BY_USER: "GET_EXAMS_BY_USER",
    ENROLL_USER_EXAM: "ENROLL_USER_EXAM",
    DELETE_USER_EXAM: "DELETE_USER_EXAM",
    GET_USEREXAM_BY_ID: "GET_USEREXAM_BY_ID",
    GET_QUESTIONS_BY_EXAM: "GET_QUESTIONS_BY_EXAM",
    ADD_QUESTION: "ADD_QUESTION",
    GET_QUESTION_BY_ID: "GET_QUESTION_BY_ID",
    GET_ALL_QUESTION: "GET_ALL_QUESTION",
    DELETE_QUESTION: "DELETE_QUESTION",
    UPDATE_QUESTION: "UPDATE_QUESTION",
    GET_DASHBOARD: "GET_DASHBOARD",
    UPDATE_OPTIONS: "UPDATE_OPTIONS",
    GET_USER_BY_NAME: "GET_USER_BY_NAME",
    CHECK_USER: "CHECK_USER"
};
